[versions]
ktx = "1.10.0"
lifecycleRuntimeKtx = "2.6.1"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
androidGradlePlugin = "8.0.1"
androidLibrary = "8.0.1"
jetbrainsKotlin  = "1.8.10"
ksp = "1.8.10-1.0.9"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }